#本地搜索,请将索引文件放在网站根目录
local_search:
  #是否启用
  enable: true

# 头部菜单，title: link
menu:
  首页: /
  标签: /tags
  归档: /archives

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3:
  - https://ipfs.fleek.co/ipfs/bafybeiciy7iswnz47f2x7zlx56isxc2s6osejvzejykijvraa63p3cwelu

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: https://storageapi.fleek.co/andoroyur-team-bucket/metaspace/wonderful-music/cover2.jpg

# 默认文章封面图（随机调用,支持外链）
cover:
  - https://storageapi.fleek.co/andoroyur-team-bucket/metaspace/wonderful-music/cover1.jpg
  - https://storageapi.fleek.co/andoroyur-team-bucket/metaspace/wonderful-music/cover2.jpg

# 网站关键字
keywords: 精彩音乐

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否启用评论功能
  enable: false
  # 是否自动展开评论框
  autoExpand: false
  # 应用编号
  clientID: ""
  # 应用秘钥
  clientSecret: ""
  # issue仓库名
  repo: ""
  # Github名
  owner: ""
  # Github名
  admin: [""]
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: false

# 链接(可选:facebook,twitter,github,wechat,email)
links:
  wechat: /img/logo.png

# 备案
beian:
  # 是否显示备案信息
  enable: false
  # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
  enableFooter: false
  # 备案号
  beianInfo: 冀ICP备xxxxxxx号
  # 链接地址
  link: http://www.beian.miit.gov.cn

# 是否使用mathjax
mathjax: true

# 是否显示 一言(hitokoto)
hitokoto: false
